### PR TITLE
1182 learn advanced functions objects prototypes and inheritance in javascript

### PR DESCRIPTION
**Pull request by jaysurya-gounder**
# Pull request

## Implement

- [ ] Update pull request (title, assignee, labels, projects, implement, measure)
- [ ] Update issue numbers here which will be fixed by this PR | Fixes #
- [ ] Update labels for clarity & PR workflow
- [ ] Add/Update comments in code
- [ ] Self code review as per this [guide](https://google.github.io/eng-practices/review/)
- [ ] Add/Update change logs, docs and release notes

## Measure

- [ ] What: Pull Request Title | Why: PR Detail | How: DIM | When: Timeline | Who: Assignee & Reviewer
- [ ] Review change logs, docs & release notes
- [ ] After completing all subtasks validate and make PR ready to merge

### CODE REVIEW

**Review by beingminimal — CHANGES_REQUESTED** [review]
cannt see all the tasks given in the link. please complete tasks as described in issue and resubmit for review

**Comment by jaysurya-gounder** [comment]
@beingminimal On Thursday we came to your office to provide us with any complex project details for the Final sem project, so please sir provide us the project details as soon as possible for PMMS Portal registration

**Comment by beingminimal** [comment]
> 

Please check Project submission discussion in codecyclecommunity. Already updated the list

**Review by beingminimal — CHANGES_REQUESTED** [review]
Please check your task #1182 . Do you really think so that you have completed all tasks of this task? Please cross check before submitting for review

**Review by beingminimal — APPROVED** [review]

**Pull request merged**
