### PR TITLE
css positioning

### PR DESCRIPTION
**Pull request by NILAYRAVAL**
# Pull request

## Implement

- [ ] Update pull request (title, assignee, labels, projects, implement, measure)
- [ ] Update issue numbers here which will be fixed by this PR | Fixes #
- [ ] Update labels for clarity & PR workflow
- [ ] Add/Update comments in code
- [ ] Self code review as per this [guide](https://google.github.io/eng-practices/review/)
- [ ] Add/Update change logs, docs and release notes

## Measure

- [ ] What: Pull Request Title | Why: PR Detail | How: DIM | When: Timeline | Who: Assignee & Reviewer
- [ ] Review change logs, docs & release notes
- [ ] After completing all subtasks validate and make PR ready to merge

### CODE REVIEW

**Comment by beingminimal** [comment]
@KunalChudasama review this

**Comment by KunalChudasama** [comment]
@NILAYRAVAL Please add the screenshot of the task in the comment...

**Comment by NILAYRAVAL** [comment]
Screenshot 2023-03-28 173502
@KunalChudasama  review please

**Comment by KunalChudasama** [comment]
> Screenshot 2023-03-28 173502 @KunalChudasama review please

**Comment by KunalChudasama** [comment]
@NILAYRAVAL Please put the Screenshot of the task....I don't want the screenshot of the output

**Comment by NILAYRAVAL** [comment]
@KunalChudasama  which type screenshot of  task vscode coding or github css positioning issue task ??????

**Comment by KunalChudasama** [comment]
@NILAYRAVAL Send me the link of your task.

**Comment by NILAYRAVAL** [comment]
@KunalChudasama https://ishadeed.com/article/learn-css-positioning/#intro

**Comment by KunalChudasama** [comment]
> @KunalChudasama https://ishadeed.com/article/learn-css-positioning/#intro

@NILAYRAVAL This link has so many examples of positioning.....what you have done..?

**Comment by NILAYRAVAL** [comment]
@KunalChudasama  Absolute Position (Eg 5)

**Review by KunalChudasama — APPROVED** [review]
Done

**Pull request merged**
